"""
BETHBot — Core Strategy Framework & Types.

Defines the strategy interface, configuration, context, and signal result types.
Strategies are pure signal generators — they MUST NOT place orders, access exchange APIs,
modify portfolio balances, or write to the database directly.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
from decimal import Decimal
from enum import StrEnum
from typing import Any

import pandas as pd
from pydantic import BaseModel, Field

from app.domain.enums import Signal
from app.domain.models import Candle

# ============================================================================
# Parameter & Portfolio Types
# ============================================================================


class ParameterType(StrEnum):
    """Supported parameter types for strategy configuration."""

    INT = "int"
    FLOAT = "float"
    BOOL = "bool"
    STRING = "string"


@dataclass
class ParameterSpec:
    """
    Describes a strategy parameter for UI rendering and validation.
    """

    name: str
    type: ParameterType
    default: Any
    min_value: Any = None
    max_value: Any = None
    description: str = ""


@dataclass
class PortfolioState:
    """
    Simplified portfolio state passed to strategies.
    """

    total_equity: Decimal = Decimal("0")
    cash_balance: Decimal = Decimal("0")
    peak_equity: Decimal = Decimal("0")
    positions: dict[str, Decimal] = field(default_factory=dict)
    unrealized_pnl: Decimal = Decimal("0")
    realized_pnl: Decimal = Decimal("0")
    daily_pnl: Decimal = Decimal("0")


# SignalDirection alias for backward compatibility
SignalDirection = Signal


# ============================================================================
# 1. Strategy Configuration
# ============================================================================


class StrategyConfiguration(BaseModel):
    """
    Configuration model for a strategy instance.
    """

    strategy_name: str = Field(description="Name of the strategy")
    version: str = Field(default="1.0.0", description="Strategy version string")
    parameters: dict[str, Any] = Field(default_factory=dict, description="Configurable parameter values")
    supported_symbols: list[str] = Field(
        default_factory=lambda: ["BTC/USDT", "ETH/USDT"],
        description="Supported market symbols",
    )


# ============================================================================
# 2. Strategy Context
# ============================================================================


@dataclass
class StrategyContext:
    """
    Context passed to a strategy during signal generation.
    Encapsulates market data, current candle, pre-calculated indicators, and timestamps.
    """

    symbol: str
    timeframe: str = "1h"
    candle: Candle | pd.Series | None = None
    market_data: pd.DataFrame | None = None
    indicators: dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    portfolio_state: PortfolioState | dict[str, Any] | None = None


# ============================================================================
# 3. Signal Result
# ============================================================================


@dataclass(frozen=True)
class SignalResult:
    """
    Immutable signal output generated by a strategy.
    """

    symbol: str = ""
    direction: Signal = Signal.HOLD  # BUY, SELL, or HOLD
    strength: float = 1.0  # 0.0 to 1.0
    confidence: float = 1.0  # 0.0 to 1.0
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    target_price: Decimal | None = None
    stop_loss: Decimal | None = None
    take_profit: Decimal | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def is_actionable(self) -> bool:
        """Return True if the signal is BUY or SELL (not HOLD)."""
        return self.direction != Signal.HOLD


# ============================================================================
# 4. Strategy Abstract Interface
# ============================================================================


class Strategy(ABC):
    """
    Abstract Strategy Interface.

    Defines the contract for strategy implementations.
    Exposes `generate_signal()` as the primary signal creation method.

    Strict Encapsulation Rules:
      - Strategies MUST NOT place orders
      - Strategies MUST NOT access exchange APIs directly
      - Strategies MUST NOT modify portfolio balances
      - Strategies MUST NOT modify database state directly
    """

    name: str = "unnamed_strategy"
    version: str = "1.0.0"

    def __init__(self, config: StrategyConfiguration | dict[str, Any] | None = None, **kwargs: Any):
        if isinstance(config, StrategyConfiguration):
            self.configuration = config
        elif isinstance(config, dict):
            self.configuration = StrategyConfiguration(
                strategy_name=self.name,
                version=self.version,
                parameters=config,
            )
        else:
            merged_params = {**kwargs}
            self.configuration = StrategyConfiguration(
                strategy_name=self.name,
                version=self.version,
                parameters=merged_params,
            )

    @classmethod
    @abstractmethod
    def parameters(cls) -> list[ParameterSpec]:
        """Declare configurable strategy parameter specifications."""
        ...

    @abstractmethod
    def initialize(self, historical_data: pd.DataFrame) -> pd.DataFrame:
        """
        Pre-compute indicators on historical market data.

        Args:
            historical_data: DataFrame with OHLCV columns [open, high, low, close, volume]

        Returns:
            DataFrame enriched with indicator columns
        """
        ...

    @abstractmethod
    def generate_signal(self, context: StrategyContext) -> SignalResult:
        """
        Generate a trading signal (BUY, SELL, or HOLD) based on current context.

        Args:
            context: StrategyContext containing market data, candle, and indicators

        Returns:
            SignalResult object indicating signal direction and metadata
        """
        ...

    def on_bar(self, bar: pd.Series | Candle, portfolio_state: Any = None) -> SignalResult:
        """
        Adapter method for bar-by-bar backtester execution.
        Constructs a StrategyContext and invokes `generate_signal()`.
        """
        symbol = getattr(bar, "symbol", "BTC/USDT")
        timeframe = getattr(bar, "timeframe", "1h")
        bar_time = getattr(bar, "open_time", getattr(bar, "name", datetime.now(timezone.utc)))

        if isinstance(bar_time, pd.Timestamp):
            dt_time = bar_time.to_pydatetime()
        elif isinstance(bar_time, datetime):
            dt_time = bar_time
        else:
            dt_time = datetime.now(timezone.utc)

        indicators = {}
        if isinstance(bar, pd.Series):
            indicators = {k: v for k, v in bar.to_dict().items() if k not in ("open", "high", "low", "close", "volume")}

        context = StrategyContext(
            symbol=symbol,
            timeframe=timeframe,
            candle=bar,
            indicators=indicators,
            timestamp=dt_time,
            portfolio_state=portfolio_state,
        )

        return self.generate_signal(context)

    def on_trade(self, trade_info: dict[str, Any]) -> None:
        """Optional callback when a trade is executed from this strategy's signal."""
        pass

    def get_state(self) -> dict[str, Any]:
        """Serialize internal state for persistence across restarts."""
        return {}

    def set_state(self, state: dict[str, Any]) -> None:
        """Restore internal state from persistence."""
        pass

    def reset(self) -> None:
        """Reset internal state. Called before running a backtest."""
        pass
