"""
BETHBot — Signal ORM model.

Represents a trading signal generated by a strategy.
"""

from __future__ import annotations

from datetime import datetime, timezone
from decimal import Decimal

from sqlalchemy import DateTime, Float, ForeignKey, Index, Integer, Numeric, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base


class Signal(Base):
    """A strategy-generated trading signal."""

    __tablename__ = "signals"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    asset_id: Mapped[int] = mapped_column(Integer, ForeignKey("assets.id"), nullable=False)
    strategy_state_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("strategy_states.id"), nullable=True
    )

    direction: Mapped[str] = mapped_column(
        String(10), nullable=False
    )  # BUY | SELL | HOLD
    strength: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    confidence: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    target_price: Mapped[Decimal | None] = mapped_column(
        Numeric(precision=20, scale=8), nullable=True
    )
    stop_loss: Mapped[Decimal | None] = mapped_column(
        Numeric(precision=20, scale=8), nullable=True
    )
    take_profit: Mapped[Decimal | None] = mapped_column(
        Numeric(precision=20, scale=8), nullable=True
    )

    metadata_json: Mapped[str | None] = mapped_column(
        String(2000), nullable=True
    )  # JSON string for extra data

    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    # Relationships
    asset = relationship("Asset", back_populates="signals")
    strategy_state = relationship("StrategyState", back_populates="signals")

    __table_args__ = (
        Index("idx_signal_strategy_time", "strategy_state_id", "generated_at"),
    )

    def __repr__(self) -> str:
        return f"<Signal {self.direction} {self.asset_id} strength={self.strength}>"
